//! # Microloop Learn — Trajectory Analysis Engine
//!
//! Analyzes agent tool-call histories and auto-generates optimal safety
//! policies. Instead of static rules, it learns an agent's operational
//! patterns from actual usage — distinguishing productive workflows from
//! destructive loops by analyzing what the agent actually does.
//!
//! ## Usage
//!
//! ```bash
//! # From a trajectory log (JSONL)
//! microloop learn --input trajectories.jsonl --output policy.yaml
//!
//! # From stdin (pipe)
//! cat trajectories.jsonl | microloop learn > policy.yaml
//!
//! # Analyze the CCR database directly
//! microloop learn --ccr ./microloop_ccr.db --output policy.yaml
//! ```

pub mod analyzer;
pub mod collector;

use analyzer::{AnalysisReport, TrajectoryEntry};
use std::io::{BufRead, BufReader, Read};

pub use analyzer::LearnedPolicy;

/// Parse a JSONL trajectory stream into entries.
pub fn parse_jsonl(input: impl Read) -> Result<Vec<TrajectoryEntry>, String> {
    let reader = BufReader::new(input);
    let mut entries = Vec::new();

    for (i, line) in reader.lines().enumerate() {
        let line = line.map_err(|e| format!("Line {}: {e}", i + 1))?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with("//") || trimmed.starts_with('#') {
            continue;
        }
        let entry: TrajectoryEntry =
            serde_json::from_str(trimmed).map_err(|e| format!("Line {}: {e}", i + 1))?;
        entries.push(entry);
    }

    Ok(entries)
}

/// Learn from a list of trajectory entries and produce a policy.
pub fn learn(entries: &[TrajectoryEntry]) -> analyzer::AnalysisReport {
    analyzer::analyze_trajectory(entries)
}

/// Render the analysis report as a YAML policy string.
pub fn render_policy(report: &AnalysisReport) -> String {
    let mut out = String::new();

    out.push_str("# Auto-generated by microloop learn\n");
    out.push_str(&format!(
        "# Based on analysis of {} tool calls across {} tools\n",
        report.total_calls,
        report.tools.len(),
    ));
    out.push_str("#\n");
    out.push_str("# Tune these values or delete this file to regenerate.\n");
    out.push_str("# Docs: https://github.com/Devaretanmay/microloop\n");
    out.push_str("---\n");

    // Global defaults
    out.push_str(&format!(
        "defaults:\n  trajectory_gate:\n    max_repeats: {}\n    count_mode: errors_only\n",
        report.suggested_global_max_repeats,
    ));

    out.push_str("\ntools:\n");

    for tool in &report.tools {
        out.push_str(&format!("  - name: {}\n", tool.name));
        out.push_str("    trajectory_gate:\n");
        out.push_str(&format!("      max_repeats: {}\n", tool.suggested_max_repeats));
        if !tool.volatile_fields.is_empty() {
            out.push_str(&format!(
                "      volatile_fields: [{}]\n",
                tool.volatile_fields
                    .iter()
                    .map(|f| format!("\"{f}\""))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        if tool.error_rate > 0.1 {
            out.push_str("      error_detection:\n");
            out.push_str("        json_path: \"$.error\"\n");
        }
        out.push_str(&format!(
            "    # calls={}, repeats={}, errors={}, error_rate={:.1}%\n",
            tool.call_count,
            tool.repeat_count,
            tool.error_count,
            tool.error_rate * 100.0,
        ));
    }

    // Append a human-readable summary
    out.push_str(&format!(
        "\n# Summary: {} tools analyzed | {} total calls | {} loops detected | {:.1}% error rate\n",
        report.tools.len(),
        report.total_calls,
        report.total_loops,
        report.global_error_rate * 100.0,
    ));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_empty_input() {
        let entries = parse_jsonl("".as_bytes()).unwrap();
        assert!(entries.is_empty());
    }

    #[test]
    fn parse_comment_lines() {
        let data = "# this is a comment\n// this too\n\n{\"tool\":\"test\",\"args\":{},\"ts\":1}\n";
        let entries = parse_jsonl(data.as_bytes()).unwrap();
        assert_eq!(entries.len(), 1);
    }

    #[test]
    fn learn_generates_valid_yaml() {
    let entries = vec![
        TrajectoryEntry {
            tool: "read_file".into(),
            args: serde_json::json!({"path": "src/main.rs"}),
            result: Some("ok".into()),
            error: false,
            ts: 1,
        },
        TrajectoryEntry {
            tool: "read_file".into(),
            args: serde_json::json!({"path": "src/main.rs"}),
            result: Some("ok".into()),
            error: false,
            ts: 2,
        },
        TrajectoryEntry {
            tool: "search".into(),
            args: serde_json::json!({"q": "rust", "sid": "abc123"}),
            result: Some("ok".into()),
            error: false,
            ts: 3,
        },
        TrajectoryEntry {
            tool: "search".into(),
            args: serde_json::json!({"q": "rust", "sid": "def456"}),
            result: Some("ok".into()),
            error: false,
            ts: 4,
        },
        TrajectoryEntry {
            tool: "delete_line".into(),
            args: serde_json::json!({"line": 5}),
            result: Some("error: line 5 not found".into()),
            error: true,
            ts: 5,
        },
        TrajectoryEntry {
            tool: "delete_line".into(),
            args: serde_json::json!({"line": 5}),
            result: Some("error: line 5 not found".into()),
            error: true,
            ts: 6,
        },
        TrajectoryEntry {
            tool: "delete_line".into(),
            args: serde_json::json!({"line": 5}),
            result: Some("error: line 5 not found".into()),
            error: true,
            ts: 7,
        },
    ];

    let report = learn(&entries);
    let yaml = render_policy(&report);

    assert!(yaml.contains("read_file"));
    assert!(yaml.contains("delete_line"));
    assert!(yaml.contains("search"));
    assert!(yaml.contains("sid"));
    assert!(yaml.contains("calls=3, repeats=2, errors=3"));
    }

    #[test]
    fn learn_detects_volatile_fields() {
        let entries = vec![
            TrajectoryEntry {
                tool: "search".into(),
                args: serde_json::json!({"query": "rust", "session_id": "abc"}),
                result: None,
                error: false,
                ts: 1,
            },
            TrajectoryEntry {
                tool: "search".into(),
                args: serde_json::json!({"query": "rust", "session_id": "xyz"}),
                result: None,
                error: false,
                ts: 2,
            },
            TrajectoryEntry {
                tool: "search".into(),
                args: serde_json::json!({"query": "async", "session_id": "def"}),
                result: None,
                error: false,
                ts: 3,
            },
        ];

        let report = learn(&entries);
        let search = report.tools.iter().find(|t| t.name == "search").unwrap();
        assert!(search.volatile_fields.contains(&"session_id".to_string()));
    }
}
