[package]
name = "microloop-python"
version = "0.1.2"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
name = "microloop_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "abi3-py38"] }
microloop = { path = "../.." }
rusqlite = { version = "0.32", features = ["bundled"] }
